/* ==========================================================================
   TOURINHALT

   Vier Führungen mit zusammen weit über hundert Schritten — reiner Text,
   der beim ersten Laden mitkam und nach der ersten Woche nie wieder
   gebraucht wurde.

   Er liegt jetzt für sich und wird geholt, wenn jemand die Tour öffnet
   oder in den Einstellungen nach ihrem Stand sieht. Wer nur seinen Plan
   aufruft, lädt ihn nie.
   ========================================================================== */

export const TOUR = {
  /* ---------------------------------------------------------------- */
  leitung: {
    titel: "Betrieb einrichten und führen",
    dauer: "25 bis 40 Minuten",
    einleitung: "Du richtest den Betrieb ein und trägst die Verantwortung für Regelwerk, Personal und Freigaben. Diese Tour führt vom leeren Bestand bis zum laufenden Plan.",
    kapitel: [
      { name: "Ankommen", punkte: [
        { titel: "Willkommen", ziel: null,
          text: "CENTRIC rechnet Dienstpläne, statt sie zu verwalten. Du hinterlegst eine Schichtfolge, und daraus entsteht jeder Tag — vorwärts wie rückwärts, ohne Jahresgrenze. Gespeichert wird nur, was von der Regel abweicht.",
          merke: "Diese Tour lässt sich jederzeit schließen und unter Einstellungen wieder starten." },
        { titel: "Die Seitenleiste", ziel: "start",
          text: "Links stehen sechs Bereiche: Heute, Planung, Anliegen, Team, Auswertung, Verwaltung. Die Zahlen daneben zeigen, wo etwas auf dich wartet.",
          tun: "Fahre einmal über alle sechs Bereiche.",
          pruefen: "Bei „Anliegen\" steht eine Zahl, wenn Anträge offen sind." },
        { titel: "Die Startseite", ziel: "start",
          text: "Oben vier Kennzahlen: offene Schichten, wartende Freigaben, Abwesenheiten heute, Lücken der nächsten sieben Tage. Darunter höchstens drei Karten mit dem, was heute zu tun ist.",
          merke: "Die Karten sind nach Dringlichkeit sortiert. Wer nur die oberste abarbeitet, hat das Wichtigste erledigt." },
        { titel: "Suche und Tastatur", ziel: null,
          text: "Oben rechts die Suche. Sie findet Personen, Dienstarten und Ansichten.",
          tun: "Tippe einen Nachnamen ein.",
          merke: "Die Eingabezeile versteht auch Sätze: „Müller krank morgen\" öffnet die Krankmeldung mit gefüllten Feldern." },
      ]},
      { name: "Betrieb einrichten", ziel: "betrieb", punkte: [
        { titel: "Standorte anlegen", ziel: "betrieb",
          text: "Jeder Standort hat ein eigenes Bundesland. Das ist keine Formalie — Feiertage unterscheiden sich, und Feiertagszuschläge hängen daran.",
          tun: "Lege für jeden Standort Bezeichnung, Bundesland und Umkreis an.",
          pruefen: "Im Monatsplan sind die Feiertage deines Bundeslandes rot markiert.",
          merke: "Der Umkreis gilt für die Standortprüfung beim Einstempeln. 200 Meter sind ein guter Anfang." },
        { titel: "Wochenarbeitszeit", ziel: "betrieb",
          text: "Die vertragliche Regelarbeitszeit einer Vollzeitkraft. Aus ihr errechnet CENTRIC die Sollstunden jedes Monats.",
          tun: "Trage die Wochenarbeitszeit ein.",
          pruefen: "Im Stundenkonto einer Vollzeitkraft steht ein Sollwert, der zur Wochenarbeitszeit passt.",
          merke: "Weicht der Wert vom Schichtmodell ab, entstehen dauerhaft Plus- oder Minusstunden. Beides muss zusammenpassen." },
        { titel: "Ruhezeit", ziel: "betrieb",
          text: "Gesetzlich elf Stunden zwischen zwei Diensten. In Pflege, Klinik und Gaststätten sind unter Bedingungen zehn zulässig.",
          tun: "Setze den Wert auf das, was bei euch gilt.",
          pruefen: "Die Prüfung meldet keine Ruhezeitverstöße, wo bisher keine waren.",
          merke: "Zu streng gesetzt erzeugt Hunderte Befunde, die niemand mehr liest. Lieber einmal mit dem Betriebsrat abstimmen." },
        { titel: "Dienste in Folge", ziel: "betrieb",
          text: "Wie viele Dienste hintereinander zulässig sind. Üblich sechs, in manchen Modellen sieben.",
          tun: "Trage die Höchstzahl ein.",
          pruefen: "Die Prüfung meldet lange Dienstserien als Hinweis." },
        { titel: "Ausgleichsgrenze", ziel: "betrieb",
          text: "Ab welchem Stand des Stundenkontos gewarnt wird. Vierzig Stunden sind verbreitet.",
          merke: "Diese Grenze ist ein Hinweis, keine Sperre. Wer sie überschreitet, wird nicht gehindert — nur sichtbar." },
        { titel: "Dienstarten anlegen", ziel: "betrieb",
          text: "Früh, Spät, Nacht — oder was bei euch gefahren wird. Name, Kürzel, Beginn, Ende, Farbe.",
          tun: "Lege jede Dienstart an. Über Mitternacht laufende Dienste werden erkannt.",
          pruefen: "Im Lagebild erscheint jede Dienstart mit einer Besetzungszahl." },
        { titel: "Dienstform wählen", ziel: "betrieb",
          text: "Regeldienst zählt voll, Bereitschaftsdienst zu 60 Prozent, Rufbereitschaft zu 12,5 Prozent. Der geteilte Dienst hat zwei Abschnitte.",
          merke: "Rufbereitschaft unterbricht die Ruhezeit nicht — deshalb ist die Dienstform wichtiger, als sie aussieht." },
        { titel: "Mindestbesetzung", ziel: "betrieb",
          text: "Je Dienstart und Wochentag getrennt: Montag bis Donnerstag, Freitag, Samstag, Sonntag.",
          tun: "Trage die Mindestbesetzung ein.",
          pruefen: "Das Lagebild zeigt Zahlen wie 8/10 — eingeteilt gegen gefordert.",
          merke: "Höher als die Gruppenstärke gesetzt, meldet die Prüfung dauerhaft Unterbesetzung." },
        { titel: "Erforderliche Qualifikationen", ziel: "betrieb",
          text: "Wenn ein Dienst ohne bestimmte Kräfte nicht laufen darf, hinterlege sie hier mit Mindestzahl.",
          pruefen: "Die Prüfung meldet fehlende Qualifikationen getrennt von fehlenden Personen." },
      ]},
      { name: "Personal", ziel: "personal", punkte: [
        { titel: "Liste einlesen", ziel: "personal",
          text: "Der schnellere Weg. Tabelle aus Excel kopieren, einfügen, fertig — die Spalten werden erkannt, auch ohne brauchbare Überschriften.",
          tun: "Team → Personal → Importieren, Tabelle einfügen, Vorschau prüfen.",
          pruefen: "Die Vorschau zeigt „sicher\", „ähnlich\" oder „aus dem Inhalt\" je Spalte. Bei „aus dem Inhalt\" nachsehen.",
          merke: "Personalnummern gleich mit einlesen — sie werden für die Lohnausgabe gebraucht." },
        { titel: "Einzeln anlegen", ziel: "personal",
          text: "Für kleine Betriebe oder Nachzügler.",
          tun: "Person hinzufügen, Name, Funktion, Einheit, Wochenstunden, Eintrittsdatum.",
          pruefen: "Die Person erscheint im Monatsplan ab dem Eintrittsdatum." },
        { titel: "Teilzeit", ziel: "personal",
          text: "Bei Teilzeit die tatsächlichen Wochenstunden eintragen. CENTRIC verteilt die Dienste entsprechend und rechnet die Sollstunden anteilig.",
          pruefen: "Das Stundenkonto einer Teilzeitkraft zeigt ein niedrigeres Soll." },
        { titel: "Einsatzeinschränkungen", ziel: "personal",
          text: "Keine Nachtdienste, kein Alleindienst, Höchstzahl Dienste je Woche, Wiedereingliederung mit Stufenplan.",
          merke: "Diese Angaben sind sensibel. Sie erscheinen in der Ersatzsuche nur als Grund, nie als Diagnose." },
        { titel: "Zugangsarten vergeben", ziel: "personal",
          text: "Organisationsleitung, Planung, Schichtverantwortung, Beschäftigte, Betriebsrat.",
          tun: "Vergib je Person die Zugangsart.",
          pruefen: "Die Person sieht beim nächsten Anmelden die neuen Ansichten.",
          merke: "Zugänge kosten nichts extra — gerechnet wird je Standort. Wer jemanden zur Planung befördert, zahlt keinen Aufpreis." },
        { titel: "Springer kennzeichnen", ziel: "personal",
          text: "Wer als Springer geführt wird, erscheint in der Ersatzsuche weiter oben und bekommt bei offenen Schichten Vorrang.",
          merke: "Springer sind für kurzfristige Ausfälle da. Wer regelmäßig im Plan steht, ist keiner." },
        { titel: "Austritt eintragen", ziel: "personal",
          text: "Statt zu löschen: Austrittsdatum setzen. Die Person verschwindet ab dann aus dem Plan, bleibt aber in Auswertung und Nachweis erhalten.",
          merke: "Löschen zerstört die Nachvollziehbarkeit vergangener Monate." },
      ]},
      { name: "Qualifikationen", ziel: "quals", punkte: [
        { titel: "Qualifikationen anlegen", ziel: "quals",
          text: "Sachkunde, Schichtleitung, Erste Hilfe, Fachweiterbildungen.",
          tun: "Bezeichnung, Kürzel und Gültigkeitsdauer eintragen.",
          pruefen: "Bei befristeten Qualifikationen erscheint in der Personalakte ein Feld für das Ablaufdatum." },
        { titel: "Fachkraft-Kennzeichen", ziel: "quals",
          text: "Wer als Fachkraft zählt, geht in die Fachkraftquote ein — den Mindestanteil examinierter Kräfte je Dienst.",
          merke: "Nur setzen, wo es fachlich stimmt. Eine falsch gesetzte Fachkraft verfälscht die ganze Quote." },
        { titel: "Gesetzlich zwingend", ziel: "quals",
          text: "Der härteste Schalter. Ohne diese Qualifikation ist gar kein Einsatz zulässig — unabhängig von der Dienstart.",
          merke: "Für die Sachkunde nach § 34a im Bewachungsgewerbe richtig. Für „wäre gut zu haben\" falsch." },
        { titel: "Personen zuordnen", ziel: "quals",
          text: "Ohne Zuordnung kann CENTRIC nicht erkennen, ob ein Dienst fachlich gedeckt ist.",
          tun: "Nutze die Matrix: Team → Qualifikationen → Matrix. Dort geht es schneller als einzeln.",
          pruefen: "Die Matrix zeigt je Einheit, wie viele Personen eine Qualifikation haben." },
        { titel: "Engpässe erkennen", ziel: "quals",
          text: "Rot in der Matrix heißt: Diese Qualifikation hängt an einer einzigen Person.",
          merke: "Eine der nützlichsten Ansichten überhaupt — sie zeigt, wo ein einziger Ausfall den Betrieb lahmlegt." },
        { titel: "Nachweise", ziel: "nachweise",
          text: "Ablaufende Qualifikationen erscheinen rechtzeitig. Läuft ein Nachweis ab, zählt die Qualifikation nicht mehr für die Besetzung.",
          pruefen: "Team → Nachweise zeigt, was in den nächsten Monaten ausläuft." },
      ]},
      { name: "Schichtfolge", ziel: "folge", punkte: [
        { titel: "Das Grundprinzip", ziel: "folge",
          text: "Statt jeden Tag einzeln zu planen, hinterlegst du einen Zyklus und den Startpunkt jeder Gruppe. Daraus wird jeder Tag berechnet.",
          merke: "Deshalb gibt es keine Jahresgrenze und keine Massenänderung, wenn das Modell wechselt." },
        { titel: "Modell wählen", ziel: "folge",
          text: "Neun geprüfte Modelle mit gerechneten Kennzahlen: Wochenstunden, Anzahl Gruppen, längste Dienstserie.",
          tun: "Planung → Schichtfolge → Einrichtungsassistent, Modell auswählen.",
          pruefen: "Die Vorschau zeigt den tatsächlichen Zyklus.",
          merke: "Die Wochenstunden müssen zur vertraglichen Arbeitszeit passen. Zwei Stunden Abweichung sind zwei Plusstunden je Woche, je Person." },
        { titel: "Eigenen Zyklus bauen", ziel: "folge",
          text: "Wenn keines passt: Dienstart antippen, dann auf die Tage klicken. Oder die Dienstart direkt auf einen Tag ziehen.",
          pruefen: "Die Kennzahlen unter dem Zyklus rechnen sich sofort neu." },
        { titel: "Gruppen und Versatz", ziel: "folge",
          text: "Jede Gruppe startet an einer anderen Stelle des Zyklus.",
          tun: "Prüfe den Versatz je Gruppe.",
          pruefen: "Im Monatsplan durchlaufen alle Gruppen dieselbe Abfolge, nur zeitversetzt.",
          merke: "Arbeiten zwei Gruppen gleichzeitig dieselbe Schicht, stimmt der Versatz nicht." },
        { titel: "Ankerdatum", ziel: "folge",
          text: "Der Tag, an dem Gruppe 1 am Zyklusanfang steht.",
          merke: "Lässt sich später ändern, verschiebt dann aber den ganzen Plan. Vor der ersten Freigabe klären." },
      ]},
      { name: "Prüfen und freigeben", ziel: "plan", punkte: [
        { titel: "Die Prüfung lesen", ziel: "pruef",
          text: "Rot ist kritisch: Ruhezeitverstoß, Unterbesetzung, fehlende Pflichtqualifikation. Gelb ist ein Hinweis.",
          tun: "Auswertung → Prüfung öffnen und die roten Befunde durchgehen.",
          pruefen: "Nach dem Beheben verschwindet der Befund sofort — die Prüfung rechnet bei jeder Änderung neu." },
        { titel: "Lücken schließen", ziel: "lage",
          text: "Bei einer unterbesetzten Dienstart auf „Besetzen\". CENTRIC schlägt Personen vor, geordnet nach Eignung.",
          tun: "Öffne einen Vorschlag und drücke „warum?\".",
          merke: "Wer nicht kann, steht unten mit Begründung. Das ist wichtiger als die Liste selbst — es erklärt sich vor dem Betriebsrat." },
        { titel: "Freigeben", ziel: "plan",
          text: "Mit der Freigabe wird der Monat verbindlich. Ab dann löst jede Änderung eine Mitteilung an die Betroffenen aus.",
          pruefen: "In der Kopfzeile steht „Freigegeben\" mit Datum und Name.",
          merke: "Vor der Freigabe ist alles Entwurf und niemand wird benachrichtigt." },
        { titel: "Planstandvergleich", ziel: "plan",
          text: "Zeigt, was sich seit der Freigabe geändert hat — und mit welchem Vorlauf.",
          merke: "Kurzfristige Änderungen sind der häufigste Streitpunkt mit dem Betriebsrat. Diese Ansicht beendet Diskussionen." },
      ]},
      { name: "Der laufende Betrieb", punkte: [
        { titel: "Krankmeldung", ziel: "lage",
          text: "Der häufigste Vorgang. Person und Zeitraum wählen — CENTRIC zeigt sofort alle entstehenden Lücken.",
          tun: "Erfasse eine Krankmeldung und schließe die Lücke.",
          pruefen: "Die Betroffenen erhalten eine Mitteilung." },
        { titel: "Offene Schichten", ziel: "offene",
          text: "Statt zehn Leute anzurufen: die Lücke ausschreiben. Wer sich meldet, darf auch — geprüft ist vorher.",
          tun: "Schreibe eine Lücke aus.",
          pruefen: "CENTRIC meldet, wie viele Personen unterrichtet wurden. Steht dort null, darf niemand." },
        { titel: "Anträge entscheiden", ziel: "antraege",
          text: "Links die Liste, rechts die Kapazität der nächsten acht Wochen. Rot heißt: diese Woche kippt erst durch diesen Antrag.",
          merke: "Mit der Tastatur geht es viel schneller: J und K blättern, G genehmigt, A lehnt ab." },
        { titel: "Belastbarkeit", ziel: "belastbarkeit",
          text: "Je Woche und Dienst: wie viele gleichzeitige Ausfälle die schwächste Schicht verträgt.",
          merke: "Einmal die Woche öffnen. Diese Ansicht zeigt Probleme, bevor sie eintreten." },
        { titel: "Verteilungsgerechtigkeit", ziel: "verteilung",
          text: "Wochenenden, Nachtdienste, Feiertage — wer trägt wie viel.",
          merke: "Die Zahl, nach der der Betriebsrat als Erstes fragt." },
        { titel: "Zeiterfassung", ziel: "abrechnung",
          text: "Beschäftigte bestätigen ihre Zeiten. Abweichungen laufen bei dir auf.",
          pruefen: "Offene Bestätigungen erscheinen als Karte auf der Startseite." },
        { titel: "Lohnausgabe", ziel: "abrechnung",
          text: "Eine Datei statt sechs Mails: Alle Stunden und Zuschläge je Person und Lohnart, fertig für die Lohnbuchhaltung.",
          merke: "CENTRIC rechnet Stunden, keine Beträge. Stundensätze gehören in die Lohnabrechnung." },
      ]},
      { name: "Verwaltung", punkte: [
        { titel: "Datenmitnahme", ziel: "mitnahme",
          text: "Sieben Tabellen als CSV, jederzeit, ohne Gebühr. Der Dienstplan wird Tag für Tag ausgeschrieben.",
          merke: "Eine Dienstplanung ist betriebskritisch. Die Frage, wie man wieder herauskommt, gehört an den Anfang." },
        { titel: "Einstellungen", ziel: "einstellungen",
          text: "Darstellung, Benachrichtigungen, diese Tour, Datenschutz und Sicherungen.",
          tun: "Sieh dir die Einstellungen einmal an.",
          merke: "Dort startest du diese Tour auch wieder, wenn du etwas nachschlagen willst." },
        { titel: "Das Handbuch", ziel: "handbuch",
          text: "Zehn Kapitel mit Suche, Fortschritt und Druckausgabe. Was diese Tour zeigt, steht dort zum Nachlesen.",
          merke: "Die Druckfassung ist zum Mitgeben gedacht — mit Deckblatt und deinem Betriebsnamen." },
        { titel: "Geschafft", ziel: null,
          text: "Du kannst jetzt einen Betrieb einrichten, Personal anlegen, eine Schichtfolge festlegen, Lücken schließen und Anträge entscheiden. Alles Weitere findest du im Handbuch.",
          merke: "Diese Tour lässt sich jederzeit unter Einstellungen erneut starten." },
      ]},
    ],
  },

  /* ---------------------------------------------------------------- */
  planer: {
    titel: "Planen, prüfen, freigeben",
    dauer: "20 bis 30 Minuten",
    einleitung: "Du führst den Plan. Diese Tour zeigt den täglichen Ablauf: Lücken erkennen, Ersatz finden, Anträge entscheiden, freigeben.",
    kapitel: [
      { name: "Ankommen", punkte: [
        { titel: "Willkommen", ziel: null,
          text: "CENTRIC rechnet den Plan aus einer Schichtfolge. Du änderst nicht den Plan, sondern trägst Abweichungen ein — Einsprünge, Tausche, Ausfälle.",
          merke: "Diese Tour lässt sich jederzeit schließen und unter Einstellungen wieder starten." },
        { titel: "Die Startseite", ziel: "start",
          text: "Vier Kennzahlen oben, darunter höchstens drei Karten mit dem, was heute zu tun ist — nach Dringlichkeit sortiert.",
          tun: "Lies die oberste Karte." },
        { titel: "Das Lagebild", ziel: "lage",
          text: "Der Tag auf einen Blick: je Dienstart eingeteilt gegen gefordert, mit Namen.",
          pruefen: "Zahlen wie 8/10 bedeuten acht eingeteilt, zehn gefordert." },
        { titel: "Die Eingabezeile", ziel: null,
          text: "Statt drei Menüs: „Müller krank morgen\" tippen. Die Krankmeldung öffnet sich mit gefüllten Feldern.",
          tun: "Probiere es mit einem Namen aus deinem Betrieb." },
      ]},
      { name: "Der Monatsplan", ziel: "plan", punkte: [
        { titel: "Aufbau", ziel: "plan",
          text: "Zeilen sind Personen, Spalten Tage. Farben zeigen die Dienstart, gestrichelte Zellen sind frei.",
          merke: "Was aus der Schichtfolge kommt, ist ruhig dargestellt. Abweichungen sind hervorgehoben." },
        { titel: "Einen Dienst ändern", ziel: "plan",
          text: "Zelle antippen, Dienstart wählen. CENTRIC zeigt vorher die Folgen: Ruhezeit, Wochenstunden, nächste Dienste.",
          pruefen: "Die Zelle ist danach als Abweichung markiert.",
          merke: "Die Regel bleibt unangetastet — du legst eine Ausnahme darüber." },
        { titel: "Mehrere auf einmal", ziel: "plan",
          text: "Mit gedrückter Maustaste über mehrere Zellen ziehen, dann die Dienstart wählen.",
          merke: "Bei mehr als zehn Zellen fragt CENTRIC nach — versehentliches Ziehen ist der häufigste Fehler." },
        { titel: "Filtern", ziel: "plan",
          text: "Nach Einheit, Dienstart, Qualifikation oder Person. Der Filter wirkt auch auf Prüfung und Auswertung.",
          tun: "Filtere auf eine einzelne Einheit." },
        { titel: "Freigeben", ziel: "plan",
          text: "Ab der Freigabe ist der Monat verbindlich und jede Änderung löst eine Mitteilung aus.",
          pruefen: "In der Kopfzeile steht „Freigegeben\" mit Datum und Name." },
      ]},
      { name: "Lücken schließen", punkte: [
        { titel: "Krankmeldung erfassen", ziel: "lage",
          text: "Person und Zeitraum wählen. CENTRIC zeigt sofort alle betroffenen Dienste.",
          tun: "Erfasse eine Krankmeldung.",
          pruefen: "Die betroffenen Dienste erscheinen im Lagebild als unterbesetzt." },
        { titel: "Ersatz suchen", ziel: "lage",
          text: "Bei der Lücke auf „Besetzen\". Wer möglich ist, steht oben; wer nicht, unten mit Grund.",
          tun: "Öffne die Ersatzliste." },
        { titel: "Die Begründung lesen", ziel: "lage",
          text: "Der Knopf „warum?\" zeigt, weshalb jemand oben steht: Stundenkonto unter dem Mittel, Wunschdienst hinterlegt, lange nicht eingesprungen.",
          merke: "Das ist der Teil, der vor dem Betriebsrat zählt. Eine Reihenfolge ohne Begründung ist Willkür." },
        { titel: "Die Folgen prüfen", ziel: "lage",
          text: "Vor dem Eintragen zeigt CENTRIC, was der Einsatz auslöst — Ruhezeit, Wochenstunden, nächste Dienste.",
          merke: "Wer abwesend ist, kann nicht eingeteilt werden. CENTRIC lehnt das ab, statt es stillschweigend anzunehmen." },
        { titel: "Erweiterte Anfrage", ziel: "lage",
          text: "Findet sich niemand: Anfrage an mehrere Personen gleichzeitig. Wer zuerst zusagt, bekommt den Dienst.",
          pruefen: "Die Angefragten erhalten eine Mitteilung." },
        { titel: "Offene Schichten ausschreiben", ziel: "offene",
          text: "Die Lücke sichtbar machen, statt herumzutelefonieren. Unterrichtet wird nur, wer sie auch nehmen darf.",
          tun: "Schreibe eine Lücke aus.",
          merke: "Die Meldungen erscheinen nach Eignung geordnet — nicht danach, wer zuerst kam." },
        { titel: "Unbesetzt lassen", ziel: "lage",
          text: "Bleibt eine Lücke: dokumentierte Unterschreitung mit Begründung.",
          merke: "Nachweisbar für Prüfungen. Besser eine begründete Lücke als ein geschönter Plan." },
      ]},
      { name: "Anliegen", ziel: "antraege", punkte: [
        { titel: "Die Antragsansicht", ziel: "antraege",
          text: "Links die Liste, rechts das Kapazitätsraster der nächsten acht Wochen.",
          pruefen: "Beim Markieren eines Antrags färben sich die betroffenen Wochen." },
        { titel: "Kapazität lesen", ziel: "antraege",
          text: "Rot heißt: diese Woche kippt erst durch diesen Antrag. Gelb: es wird eng.",
          merke: "Mehrere auswählen zeigt die Wirkung aller zusammen — wichtig bei der Urlaubsrunde." },
        { titel: "Mit der Tastatur", ziel: "antraege",
          text: "J und K blättern, G genehmigt, A lehnt ab, Leertaste wählt aus.",
          merke: "Bei vierzig Anträgen ist das der Unterschied zwischen zwanzig Minuten und fünf." },
        { titel: "Mehrstufige Genehmigung", ziel: "antraege",
          text: "Manche Anträge brauchen zwei Freigaben. Dann steht dort „Stufe 1 von 2\" und „Mitzeichnen\".",
          merke: "Erst mit der letzten Stufe wird der Antrag umgesetzt." },
        { titel: "Tauschbörse", ziel: "boerse",
          text: "Beschäftigte bieten Dienste an und suchen Tausche. Du bestätigst — oder lässt es laufen.",
          merke: "Ein bestätigter Tausch erzeugt zwei Abweichungen, keine Änderung an der Schichtfolge." },
        { titel: "Wunschdienste", ziel: "wuensche",
          text: "Wer Wünsche hinterlegt, erscheint bei passenden Diensten weiter oben in der Ersatzsuche.",
          merke: "Wünsche sind kein Anspruch. Sie verschieben nur die Reihenfolge." },
      ]},
      { name: "Auswertung", punkte: [
        { titel: "Die Prüfung", ziel: "pruef",
          text: "Rot ist kritisch, gelb ein Hinweis. Jeder Befund nennt Person, Datum und Grund.",
          tun: "Öffne die Prüfung und klicke einen Befund an." },
        { titel: "Belastbarkeit", ziel: "belastbarkeit",
          text: "Wie viele gleichzeitige Ausfälle jede Woche verträgt. Null heißt: der nächste Krankheitsfall reißt ein Loch.",
          merke: "Einmal die Woche öffnen — das ist die Ansicht, die Überraschungen verhindert." },
        { titel: "Ausfallszenarien", ziel: "belastbarkeit",
          text: "Vier Stufen von fünf bis dreißig Prozent. Zeigt, ab wann der Betrieb kippt.",
          merke: "Nützlich für das Gespräch über Personalbedarf — mit Zahlen statt Gefühl." },
        { titel: "Verteilung", ziel: "verteilung",
          text: "Wochenenden, Nachtdienste, Feiertage je Person.",
          merke: "Die Zahl, nach der der Betriebsrat als Erstes fragt." },
        { titel: "Planungssicherheit", ziel: "planstand",
          text: "Wie oft der freigegebene Plan noch geändert wurde und mit welchem Vorlauf.",
          merke: "Eine niedrige Zahl ist ein besseres Verkaufsargument als jede Zusage." },
        { titel: "Zeiterfassung", ziel: "abrechnung",
          text: "Was bestätigt ist, was abweicht, was offen bleibt.",
          pruefen: "Offene Bestätigungen erscheinen als Karte auf der Startseite." },
      ]},
      { name: "Zum Schluss", punkte: [
        { titel: "Einstellungen", ziel: "einstellungen",
          text: "Darstellung, Benachrichtigungen, diese Tour.",
          tun: "Sieh dir an, was du einstellen kannst." },
        { titel: "Das Handbuch", ziel: "handbuch",
          text: "Zum Nachschlagen, mit Suche und Druckausgabe." },
        { titel: "Geschafft", ziel: null,
          text: "Du kannst jetzt Lücken schließen, Ersatz begründet auswählen, Anträge mit Blick auf die Folgen entscheiden und den Plan freigeben.",
          merke: "Die Tour lässt sich unter Einstellungen erneut starten." },
      ]},
    ],
  },

  /* ---------------------------------------------------------------- */
  subplaner: {
    titel: "Die eigene Einheit führen",
    dauer: "12 bis 18 Minuten",
    einleitung: "Du führst deine Einheit und fährst selbst mit. Diese Tour zeigt, was du ändern darfst — und wo die Grenze liegt.",
    kapitel: [
      { name: "Ankommen", punkte: [
        { titel: "Willkommen", ziel: null,
          text: "Du siehst und änderst deine Einheit. Der übrige Betrieb bleibt sichtbar, aber unveränderlich.",
          merke: "Diese Tour lässt sich unter Einstellungen erneut starten." },
        { titel: "Deine Grenze", ziel: "start",
          text: "Was außerhalb deiner Einheit liegt, ist ausgegraut. Ein Versuch dort meldet, warum es nicht geht.",
          merke: "Das ist Absicht: Wer alles ändern darf, trägt auch die Verantwortung für alles." },
        { titel: "Du fährst mit", ziel: "meine",
          text: "Anders als die Planung stehst du selbst im Plan. Unter „Meine Schichten\" siehst du deine Dienste.",
          pruefen: "Dort steht dein nächster Dienst mit Datum und Zeit." },
      ]},
      { name: "Alltag", punkte: [
        { titel: "Das Lagebild", ziel: "lage",
          text: "Der Tag deiner Einheit: eingeteilt gegen gefordert.",
          tun: "Öffne das Lagebild und sieh dir heute an." },
        { titel: "Krankmeldung", ziel: "lage",
          text: "Für Personen deiner Einheit erfassbar. Die Lücken erscheinen sofort.",
          tun: "Erfasse eine Krankmeldung." },
        { titel: "Ersatz suchen", ziel: "lage",
          text: "Vorschläge nach Eignung, mit Begründung. Der Knopf „warum?\" erklärt die Reihenfolge.",
          merke: "Wer nicht kann, steht unten mit Grund — Ruhezeit, Qualifikation, Abwesenheit." },
        { titel: "Über die Einheit hinaus", ziel: "lage",
          text: "Findet sich in deiner Einheit niemand, kannst du eine Anfrage an die Planung stellen.",
          pruefen: "Die Anfrage erscheint bei der Planung unter Anliegen." },
        { titel: "Offene Schichten", ziel: "offene",
          text: "Lücken deiner Einheit ausschreiben, statt herumzutelefonieren.",
          merke: "Unterrichtet wird nur, wer die Schicht auch übernehmen darf." },
        { titel: "Schichtübergabe", ziel: "uebergabe",
          text: "Lage, offene Aufgaben, Vorkommnisse, Material. Nach dem Abschließen unveränderlich.",
          merke: "Die Unveränderbarkeit ist Absicht — eine nachträglich geänderte Übergabe wäre als Nachweis wertlos." },
      ]},
      { name: "Anliegen und Auswertung", punkte: [
        { titel: "Anträge deiner Einheit", ziel: "antraege",
          text: "Du siehst die Anträge deiner Leute und kannst mitzeichnen.",
          merke: "Bei mehrstufiger Genehmigung bist du oft Stufe 1, die Planung Stufe 2." },
        { titel: "Zeiten bestätigen", ziel: "abrechnung",
          text: "Was deine Leute erfasst haben, läuft bei dir auf.",
          pruefen: "Offene Bestätigungen erscheinen auf der Startseite." },
        { titel: "Belastbarkeit", ziel: "belastbarkeit",
          text: "Wie viele Ausfälle deine Einheit verträgt.",
          merke: "Steht dort null, ruf lieber vorher bei der Planung an als hinterher." },
      ]},
      { name: "Zum Schluss", punkte: [
        { titel: "Einstellungen", ziel: "einstellungen",
          text: "Darstellung, Benachrichtigungen, diese Tour." },
        { titel: "Geschafft", ziel: null,
          text: "Du kannst deine Einheit führen: Ausfälle erfassen, Ersatz finden, übergeben und Zeiten bestätigen.",
          merke: "Alles Weitere steht im Handbuch." },
      ]},
    ],
  },

  /* ---------------------------------------------------------------- */
  mitarbeiter: {
    titel: "Deine Dienste auf dem Telefon",
    dauer: "5 bis 8 Minuten",
    einleitung: "Kurz und praktisch: wann du arbeitest, wie du Anträge stellst und Zeiten bestätigst.",
    kapitel: [
      { name: "Das Wichtigste", punkte: [
        { titel: "Wann arbeite ich?", ziel: "heute",
          text: "Der Reiter „Heute\" zeigt ganz oben deinen Dienst — mit Zeit, Ort und Dauer.",
          tun: "Sieh nach, wann dein nächster Dienst ist.",
          pruefen: "Steht dort „frei\", hast du heute keinen Dienst." },
        { titel: "Ein- und ausstempeln", ziel: "heute",
          text: "Der große Knopf auf der Startseite. Beim Stempeln wird einmalig geprüft, ob du am Einsatzort bist.",
          merke: "Gespeichert wird nur, ob du dort warst — keine Koordinate, kein Verlauf, keine Dauerortung." },
        { titel: "Mein Plan", ziel: "meinplan",
          text: "Kommende Dienste als Liste oder Monatsansicht. Filter für nur Dienste, nur frei, Nachtdienste, Wochenende.",
          tun: "Wechsle einmal zwischen Liste und Monat." },
      ]},
      { name: "Anliegen", punkte: [
        { titel: "Urlaub beantragen", ziel: "anliegen",
          text: "Zeitraum wählen, absenden. Du siehst sofort deinen Urlaubsrest.",
          pruefen: "Der Antrag erscheint mit Stand „offen\"." },
        { titel: "Krank melden", ziel: "anliegen",
          text: "Zeitraum eintragen. Die Planung wird sofort unterrichtet.",
          merke: "Die Krankmeldung ersetzt nicht die Meldung an deinen Betrieb — sie ergänzt sie." },
        { titel: "Tauschen", ziel: "meinplan",
          text: "Dienst antippen, Tausch suchen. Dein Gesuch sehen alle, die den Dienst übernehmen dürfen.",
          pruefen: "Meldet sich jemand, bekommst du eine Mitteilung." },
        { titel: "Offene Schichten", ziel: "offene",
          text: "Dienste, die du zusätzlich übernehmen kannst. Hier steht nur, was du auch wirklich darfst.",
          merke: "Ruhezeit, Qualifikation und deine Abwesenheiten sind bereits geprüft." },
        { titel: "Wunschdienste", ziel: "mehr",
          text: "Hinterlege, welche Dienste dir lieber sind. Das verschiebt die Reihenfolge bei der Ersatzsuche.",
          merke: "Ein Wunsch ist kein Anspruch — aber er wird berücksichtigt." },
      ]},
      { name: "Zeiten und Konto", punkte: [
        { titel: "Zeiten bestätigen", ziel: "anliegen",
          text: "Nach dem Dienst: „wie geplant\" oder mit Abweichung.",
          pruefen: "Bestätigte Zeiten verschwinden aus der Liste." },
        { titel: "Stundenkonto", ziel: "anliegen",
          text: "Dein Stand mit Verlauf über sechs Monate.",
          merke: "Minus heißt nicht Schulden — es gleicht sich über den Zyklus aus." },
        { titel: "Nachweise", ziel: "mehr",
          text: "Deine Qualifikationen und wann sie ablaufen.",
          pruefen: "Läuft etwas bald ab, erscheint ein Hinweis." },
      ]},
      { name: "Zum Schluss", punkte: [
        { titel: "Benachrichtigungen", ziel: "mehr",
          text: "Unter Mehr stellst du ein, worüber du unterrichtet wirst — per E-Mail oder auf dem Gerät.",
          tun: "Schalte Mitteilungen auf diesem Gerät ein.",
          merke: "Ohne sie erfährst du von Änderungen erst beim nächsten Öffnen." },
        { titel: "Geschafft", ziel: null,
          text: "Du weißt jetzt, wann du arbeitest, wie du Anträge stellst, tauschst und Zeiten bestätigst.",
          merke: "Die Tour lässt sich unter Mehr erneut starten." },
      ]},
    ],
  },

  /* ---------------------------------------------------------------- */
  betriebsrat: {
    titel: "Prüfen und mitbestimmen",
    dauer: "10 bis 15 Minuten",
    einleitung: "Du hast lesenden Zugriff auf alles, was für die Mitbestimmung nötig ist. Diese Tour zeigt, wo die Zahlen stehen.",
    kapitel: [
      { name: "Ankommen", punkte: [
        { titel: "Willkommen", ziel: null,
          text: "Dein Zugang ist rein lesend. Du kannst nichts ändern — und niemand kann behaupten, du hättest.",
          merke: "Der Betriebsratszugang ist kostenfrei. Das ist Absicht: Mitbestimmung darf nicht am Preis scheitern." },
        { titel: "Was du siehst", ziel: "start",
          text: "Plan, Prüfung, Verteilung, Planungssicherheit, Protokoll. Nicht sichtbar: Krankheitsgründe und persönliche Notizen.",
          merke: "Diese Trennung ist bewusst — Mitbestimmung braucht Zahlen, keine Diagnosen." },
      ]},
      { name: "Die Zahlen", punkte: [
        { titel: "Verteilungsgerechtigkeit", ziel: "verteilung",
          text: "Wochenenden, Nachtdienste, Feiertage je Person — mit Abweichung vom Mittel.",
          tun: "Sieh dir an, wer über dem Mittel liegt.",
          merke: "Die wichtigste Ansicht für dich. Ungleiche Verteilung ist der häufigste Streitpunkt." },
        { titel: "Die Prüfung", ziel: "pruef",
          text: "Alle Befunde gegen Arbeitszeitgesetz, Mindestbesetzung und Qualifikationen.",
          pruefen: "Rote Befunde sind kritisch, gelbe Hinweise." },
        { titel: "Planungssicherheit", ziel: "planstand",
          text: "Wie oft der freigegebene Plan geändert wurde und mit welchem Vorlauf.",
          merke: "Kurzfristige Änderungen sind mitbestimmungspflichtig. Hier stehen sie mit Datum." },
        { titel: "Belastbarkeit", ziel: "belastbarkeit",
          text: "Wie viele Ausfälle jede Woche verträgt. Null bedeutet dauerhafte Unterbesetzung.",
          merke: "Nützlich für das Gespräch über Personalbedarf — mit Zahlen statt Behauptungen." },
        { titel: "Das Protokoll", ziel: "buch",
          text: "Wer hat wann was geändert.",
          merke: "Nachvollziehbarkeit ist die Grundlage jeder Mitbestimmung." },
      ]},
      { name: "Zum Schluss", punkte: [
        { titel: "Einstellungen", ziel: "einstellungen",
          text: "Darstellung, Benachrichtigungen, diese Tour." },
        { titel: "Geschafft", ziel: null,
          text: "Du weißt jetzt, wo Verteilung, Prüfbefunde, Planungssicherheit und Protokoll stehen.",
          merke: "Die Tour lässt sich unter Einstellungen erneut starten." },
      ]},
    ],
  },

  /* ---------------------------------------------------------------- */
  betreiber: {
    titel: "Mandanten und Abrechnung",
    dauer: "10 bis 15 Minuten",
    einleitung: "Du führst die Betreiberkonsole: Mandanten anlegen, Zugänge vergeben, Rechnungen erzeugen.",
    kapitel: [
      { name: "Mandanten", punkte: [
        { titel: "Die Übersicht", ziel: "mandanten",
          text: "Alle Betriebe mit Standorten, Personenzahl, Tarif und Monatspreis.",
          merke: "Du siehst Kennzahlen, keine Personendaten. Kein Name, kein Dienstplan — das gehört den Betrieben." },
        { titel: "Mandant anlegen", ziel: "mandanten",
          text: "Name, Branche, Anschrift, Ansprechpartner. CENTRIC erzeugt daraufhin die Zugänge.",
          pruefen: "Die Zugangscodes erscheinen unmittelbar nach dem Anlegen — notiere sie, sie sind später nicht wiederherstellbar." },
        { titel: "Leerer Bestand", ziel: "mandanten",
          text: "Ein neu angelegter Mandant startet ohne Daten. Kein Beispielpersonal, keine erfundenen Dienstpläne.",
          merke: "Bei den Demozugängen ist das anders — dort steht ein vollständiger Beispielbetrieb." },
        { titel: "Zugänge nachträglich", ziel: "mandanten",
          text: "Weitere Zugänge lassen sich jederzeit erzeugen, etwa wenn die Planung wechselt.",
          pruefen: "Der neue Code erscheint in der Liste des Mandanten." },
        { titel: "Geänderte Anmeldungen", ziel: "mandanten",
          text: "Wenn jemand seine Anmeldeadresse ändert, erscheint das hier mit Datum.",
          merke: "So merkst du, wenn ein Zugang den Besitzer wechselt." },
      ]},
      { name: "Abrechnung", punkte: [
        { titel: "Das Preismodell", ziel: "rechner",
          text: "Gerechnet wird je Standort, nicht je Kopf. Wer einstellt, zahlt nicht mehr.",
          merke: "Der Punkt, an dem du gegen Anbieter mit Kopfpauschale gewinnst — bei mehreren Standorten deutlich." },
        { titel: "Tarife pflegen", ziel: "tarife",
          text: "Preis je Standort und die Personengrenze, ab der ein Standort in den nächsten Tarif steigt.",
          merke: "Größere Standorte steigen automatisch auf. Ein Betrieb zahlt für die Zentrale mehr als für eine Außenstelle." },
        { titel: "Rechnungen", ziel: "rechnungen",
          text: "Je Standort eine Zeile, Mengenstaffel und Branchenpakete getrennt ausgewiesen.",
          pruefen: "Ein unterjährig begonnener Vertrag wird tagesgenau anteilig berechnet." },
        { titel: "Branchenpakete", ziel: "pakete",
          text: "Sicherheit, Pflege, Klinik, Industrie. Jedes schaltet Funktionen und Begriffe frei.",
          merke: "Pakete werden je Betrieb berechnet, nicht je Standort." },
      ]},
      { name: "Zum Schluss", punkte: [
        { titel: "Einstellungen", ziel: "einstellungen",
          text: "Darstellung, Benachrichtigungen, diese Tour." },
        { titel: "Geschafft", ziel: null,
          text: "Du kannst Mandanten anlegen, Zugänge vergeben und Rechnungen erzeugen.",
          merke: "Die Tour lässt sich unter Einstellungen erneut starten." },
      ]},
    ],
  },
};
